language: cpp
os:
    - osx
compiler:
    - gcc
notifications:
    email: false
env:
    matrix:
        - JULIAVERSION="releases"
        - JULIAVERSION="nightlies"
before_install:
    - ./CI/install_julia_osx.sh
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'versioninfo(); Pkg.init(); Pkg.clone(pwd())'
    - julia test/tests.jl
after_success:
    - julia -e 'cd(Pkg.dir("Homebrew")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
