language: julia
matrix:
    include:
        - os: osx
          osx_image: xcode7.3
          julia: 0.4
        - os: osx
          osx_image: xcode7.3
          julia: 0.5
        - os: osx
          osx_image: xcode7.3
          julia: nightly
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("Homebrew")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
