language: cpp
os:
    - osx
compiler:
    - gcc
notifications:
    email: false
env:
    matrix:
        - JULIAVERSION="releases"
        - JULIAVERSION="nightlies"
before_install:
    - uname -a
    - if [[ "$JULIAVERSION" == "releases" ]]; then wget -O julia.dmg http://status.julialang.org/download/osx10.7+; fi
    - if [[ "$JULIAVERSION" == "nightlies" ]]; then wget -O julia.dmg http://status.julialang.org/download/osx10.7+; fi
    - hdiutil mount julia.dmg
    - cp -Ra /Volumes/Julia/*.app/Contents/Resources/julia/ ~
    - export PATH="$PATH:$(echo ~)/bin"
    - which julia
    - ls ~/bin
    - ls ~/lib/julia
script:
    - julia -e 'println(GIT_VERSION_INFO.commit)'
after_success:
    - julia -e 'cd(Pkg.dir("Homebrew")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
